[Service]
Host = "localhost"
JWTPrivKey = "res/rsa/app.rsa"
JWTPubKey = "res/rsa/app.rsa.pub"
Labels = ["edgex club"]
OpenMsg = "edgex club server started"
Port = 8080
StaticResourcePath = "./static"

[Database]
DatabaseName = "edgex-club"
Host = "39.98.39.186"
Password = ""
Port = 8080
Username = ""

[Certificate]
CertPath = "res/tls/"
Crt = "res/tls/edgex-club-nginx.crt"
Key = "res/tls/edgex-club-nginx.key"
