[Service]
Host = "localhost"
Labels = ["edgex-club"]
Port = 8080
StartupMsg = "edgex club server started."
StaticResourcePath = "./static"

[Env]
Prod = false

[Database]
DatabaseName = "edgex-club"
Host = "39.98.39.186"
Password = ""
Port = 8080
Username = ""

[Certificate]
Crt = ""
Key = ""

[GitHub]
ClientId = "8dc598397ad0cc13bed8"
Secret = "5d4ceb59b837b846cfd5ce7416af5dbc8a89b241"
