[Service]
Host = "localhost"
Labels = ["edgex-club"]
Port = 8080
StartupMsg = "edgex club server started."
StaticResourcePath = "./static"

[Env]
Prod = false

[Database]
DatabaseName = "edgex-club"
Host = "39.98.39.186"
Password = ""
Port = 8080
Username = ""

[Certificate]
Crt = ""
Key = ""

[GitHub]
ClientId = ""
Secret = ""
