[Service]
Host = "edgexfoundry.club"
Labels = ["edgex-club"]
Port = 443
StartupMsg = "edgex club server started."
StaticResourcePath = "./static"

[Env]
Prod = true

[Database]
DatabaseName = "edgex-club"
Host = "localhost"
Password = ""
Port = 0
Username = ""

[Certificate]
Crt = "res/tls/edgex-club-nginx.crt"
Key = "res/tls/edgex-club-nginx.key"

[GitHub]
ClientId = ""
Secret = ""
