[Service]
Host = "edgexfoundry.club"
JWTKey = "edgexfoundry.club"
Labels = ["edgex club"]
OpenMsg = "edgex club server started"
Port = 8080
StaticResourcePath = "./static"

[Database]
DatabaseName = "edgex-club"
Host = "localhost"
Password = ""
Port = 8500
Username = ""

[Certificate]
CertPath = "res/tls"
Crt = "edgex-club-nginx.crt"
Key = "edgex-club-nginx.key"
